server:
  port: 8006

spring:
  application:
    name: 'ui-cad'
  redis:
    host: ${redis.host}
  thymeleaf:
    cache: false
  jackson:
    serialization-inclusion: NON_EMPTY

security:
  sessions: never    
    
eureka:
  instance:
    prefer-ip-address: true
    healthCheckUrlPath: /health
    instance-enabled-onit: true
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
    use-dns-for-fetching-service-urls: false

logging:
  level:
    root: INFO
    com.netflix: INFO
    org.apache.coyote: INFO
    org.apache.http: INFO
    org.springframework.security.web.access: INFO
    org.springframework.security.access.vote: INFO