package com.acsp.salesprocess.dto;

public enum ApplicationStatus {

	APPLICATION_LOGIN,
	ACCEPTED,
	FIRST_VERIFICATION,
	FIRST_EXAMINATION,
	FINAL_EXAMINATION_OVER,
	CONTRACT_LOGIN_OVER,
	APPLICATION_CANCEL,
	WAITING_FOR_1ST_VERIFICATION,
	FIRST_ASSESSMENT,
	FINAL_VERIFICATION,
	FINAL_ASSESSMENT,
	WAITING_FOR_FINAL_VERIFICATION,
	WAITING_FOR_BAP_VERIFICATION;
	
}
