server:
  port: 3347
  
spring:
  application:
    name: 'command-send-sales-key'
  redis:
    host: ${redis.host}
  datasource:
    dataSourceClassName: oracle.jdbc.pool.OracleDataSource
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    
eureka:
  instance:
    prefer-ip-address: true
    healthCheckUrlPath: /health
    instance-enabled-onit: true
  client:
    serviceUrl:
      defaultZone: ${eureka.client.osa.serviceUrl.defaultZone}
    use-dns-for-fetching-service-urls: false

logging:
  level:
    root: INFO
    com:
      acsp: DEBUG