server:
  port: 8070

spring:
  application:
    name: 'command-reset-password'
  redis:
    host: ${redis.host}
  jackson:
    serialization-inclusion: NON_EMPTY
  datasource:
    dataSourceClassName: oracle.jdbc.pool.OracleDataSource
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 3000000
    idleTimeout: 3000000
    pool-prepared-statements: true
    max-open-prepared-statements: 250  
    
security:
  sessions: never
    
eureka:
  instance:
    prefer-ip-address: true
    healthCheckUrlPath: /health
    instance-enabled-onit: true
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
    use-dns-for-fetching-service-urls: false

logging:
  level:
    root: INFO
    org.jooq: DEBUG
